### ISSUE TITLE
Error when loading dataset "usail-hkust/JailJudge"

### ISSUE THREAD

**Issue by MichaelFu1998-create** [usail-hkust/Jailjudge#1]
Hi there,
Thanks for sharing the dataset!

I tried to load the dataset using:  

```python  
from datasets import load_dataset  
dataset = load_dataset("usail-hkust/JailJudge")  
```  

I encountered the following error:  

```
Failed to load JSON file "JAILJUDGE_TRAIN.json" with error:  
pyarrow.lib.ArrowInvalid: JSON parse error: Invalid value in row 0  

Traceback (most recent call last):  
  ...  
ValueError: Expected object or value  

datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset  
```

It seems the JSON file in the dataset is either malformed or incompatible with the expected format.

**Comment by MGYN** [comment]
Hi, can you share how to solve this?

**Comment by DreamChaser256** [comment]
> Hi there, Thanks for sharing the dataset!
> 
> I tried to load the dataset using:
> 
> from datasets import load_dataset  
> dataset = load_dataset("usail-hkust/JailJudge")  
> I encountered the following error:
> 
> ```
> Failed to load JSON file "JAILJUDGE_TRAIN.json" with error:  
> pyarrow.lib.ArrowInvalid: JSON parse error: Invalid value in row 0  
> 
> Traceback (most recent call last):  
>   ...  
> ValueError: Expected object or value  
> 
> datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset  
> ```
> 
> It seems the JSON file in the dataset is either malformed or incompatible with the expected format.

I also encountered the same problem. Have you solved it? Please feel free to give me some advice.

**Comment by MichaelFu1998-create** [comment]
Hi @DreamChaser256 
I ended up downloading manually here: https://huggingface.co/datasets/usail-hkust/JailJudge/blob/main/JAILJUDGE_TRAIN.json
You can also find multiple versions from the commit history.
Hope this helps.
